spring:
  application:
    name: proxy_service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    routes:
      - id: microservice_route
        uri: lb://MICROSERVICE_WORKSHP_MAVEN
        predicates:
          - Path=/categories/**


  config:
    enabled: false
    uri: http://localhost:8888

  server:
    port: 8780

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/